In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
#sns.get_dataset_names()

In [3]:
df = sns.load_dataset('iris')
print(df)
labels = np.unique(np.array(df['species']))
labels

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]


array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [4]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [5]:
# Encoding the categorical values with integers
#{'setosa': 1, 'versicolor': 2, 'virginica': 3}
species=np.unique(df['species'])
idx=1
d1,d2={},{}
for s in species:
    d1[s]=idx
    idx+=1
print(d1)
encode={'species':d1}
df=df.replace(encode)
df

{'setosa': 1, 'versicolor': 2, 'virginica': 3}


sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        1
1             4.9          3.0           1.4          0.2        1
2             4.7          3.2           1.3          0.2        1
3             4.6          3.1           1.5          0.2        1
4             5.0          3.6           1.4          0.2        1
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        3
146           6.3          2.5           5.0          1.9        3
147           6.5          3.0           5.2          2.0        3
148           6.2          3.4           5.4          2.3        3
149           5.9          3.0           5.1          1.8        3

[150 rows x 5 columns]

In [6]:
# df.dtypes

In [7]:
# splitting dataset in 80:20 ratio as train and test set respectively
# species is the response variable i.e. column 0
idx = 8*df.shape[0]//10
df = np.array(df)
np.random.shuffle(df)
x_train=df[0:idx,:-1]
y_train=df[0:idx,-1]
x_test=df[idx:,:-1] 
y_test=df[idx:,-1] 
print("\nx train:\n",x_train)
print("\ny train:\n",y_train)
print("\nx test:\n",x_test)
print("\ny test:\n",y_test)


x train:
 [[6.1 3.  4.6 1.4]
 [5.8 2.7 5.1 1.9]
 [5.  3.6 1.4 0.2]
 [7.9 3.8 6.4 2. ]
 [7.2 3.  5.8 1.6]
 [5.9 3.  5.1 1.8]
 [6.3 2.5 4.9 1.5]
 [6.3 2.7 4.9 1.8]
 [6.8 3.2 5.9 2.3]
 [6.3 3.3 6.  2.5]
 [6.7 3.1 4.7 1.5]
 [6.4 3.2 5.3 2.3]
 [4.7 3.2 1.6 0.2]
 [5.7 2.9 4.2 1.3]
 [5.1 3.5 1.4 0.2]
 [4.9 3.6 1.4 0.1]
 [6.7 2.5 5.8 1.8]
 [6.  2.9 4.5 1.5]
 [6.3 2.9 5.6 1.8]
 [5.5 3.5 1.3 0.2]
 [5.  3.4 1.6 0.4]
 [6.9 3.1 5.1 2.3]
 [6.7 3.1 5.6 2.4]
 [5.4 3.7 1.5 0.2]
 [7.7 2.6 6.9 2.3]
 [6.3 2.8 5.1 1.5]
 [6.2 2.2 4.5 1.5]
 [4.8 3.  1.4 0.3]
 [5.8 2.8 5.1 2.4]
 [4.9 3.1 1.5 0.2]
 [5.2 3.5 1.5 0.2]
 [4.3 3.  1.1 0.1]
 [5.  3.2 1.2 0.2]
 [5.6 3.  4.5 1.5]
 [7.3 2.9 6.3 1.8]
 [4.6 3.4 1.4 0.3]
 [6.4 2.9 4.3 1.3]
 [6.2 2.8 4.8 1.8]
 [6.3 3.3 4.7 1.6]
 [5.2 2.7 3.9 1.4]
 [6.7 3.3 5.7 2.5]
 [5.  3.5 1.3 0.3]
 [6.1 2.8 4.  1.3]
 [5.7 3.  4.2 1.2]
 [4.4 2.9 1.4 0.2]
 [5.2 4.1 1.5 0.1]
 [4.4 3.2 1.3 0.2]
 [5.1 3.5 1.4 0.3]
 [5.8 2.7 4.1 1. ]
 [7.2 3.6 6.1 2.5]
 [6.  2.2 4.  1. ]
 [5.7 4.4 1.5 0.4]
 

In [8]:
from math import sqrt

#finds mean and standard deviation for each column
def find_stats(ds):
    mean=[]
    std=[]
    for c in range(ds.shape[1]):
        mean.append(np.mean(ds[:,c]))
        std.append(np.std(ds[:,c]))
    return mean,std

# We find mean and standard deviation for each class
def stats_by_class(x,y):
    classes = np.unique(y)
    groups={c:[] for c in classes}
    for row in range(y.shape[0]):
        c = y[row]
        groups[c].append(x[row,:])
    
    stats={}
    i=0
    for cl,rows in groups.items():
        mean,std = find_stats(np.array(rows))
        stats[cl]=[mean,std,len(rows)]
        i+=1
    return stats
    
def gaussian_prob(x_i,mean,std):
    return (1/(sqrt(2*np.pi)*std))*np.exp((-1*(x_i-mean)**2)/(2*(std**2)))

def find_prob_for_class(stats,row):
    total_rows=0
    for key in stats.keys():
        total_rows+=stats[key][2]
    prob={}
    for cl in stats.keys():
        prob[cl]=(stats[cl][2]/total_rows)
        #print(prob[cl])
        for i in range(len(stats[cl][0])):
            mean = stats[cl][0][i]
            std = stats[cl][1][i]
            #print(mean,std)
            val = gaussian_prob(row[i],mean,std)
            prob[cl]*=val
    return prob

def predict(stats,test_row):
    prob=find_prob_for_class(stats,test_row)
    #print(prob)
    label,best_prob=None,None
    for key in prob.keys():
        if best_prob is None or best_prob<prob[key]:
            best_prob=prob[key]
            label=key
    return label

def calAccuracy(pred,y_):
    correct=0
    for i in range(y_.shape[0]):
        if pred[i]==y_[i]:
            correct+=1
    return correct*100/y_.shape[0]

def show_predictions(pred,y_):
    for i in range(y_.shape[0]):
        print(f"predicted value: {pred[i]}",end='\t')
        print(f"actual value: {y_[i]}")

In [9]:
stats = stats_by_class(x_train,y_train)
predictions=[]
for r in range(x_test.shape[0]):
    label = predict(stats,x_test[r,:])
    predictions.append(label)
accuracy = calAccuracy(predictions, y_test)
print(f"model's accuracy: {accuracy}%")

model's accuracy: 96.66666666666667%


In [10]:
show_predictions(predictions,y_test)

predicted value: 1.0	actual value: 1.0
predicted value: 2.0	actual value: 2.0
predicted value: 1.0	actual value: 1.0
predicted value: 3.0	actual value: 3.0
predicted value: 3.0	actual value: 3.0
predicted value: 2.0	actual value: 2.0
predicted value: 2.0	actual value: 2.0
predicted value: 2.0	actual value: 2.0
predicted value: 1.0	actual value: 1.0
predicted value: 2.0	actual value: 2.0
predicted value: 3.0	actual value: 3.0
predicted value: 2.0	actual value: 2.0
predicted value: 3.0	actual value: 3.0
predicted value: 1.0	actual value: 1.0
predicted value: 1.0	actual value: 1.0
predicted value: 2.0	actual value: 2.0
predicted value: 3.0	actual value: 3.0
predicted value: 1.0	actual value: 1.0
predicted value: 3.0	actual value: 2.0
predicted value: 3.0	actual value: 3.0
predicted value: 1.0	actual value: 1.0
predicted value: 1.0	actual value: 1.0
predicted value: 2.0	actual value: 2.0
predicted value: 2.0	actual value: 2.0
predicted value: 1.0	actual value: 1.0
predicted value: 2.0	actu