<a href="https://colab.research.google.com/github/tanya12181/Machine-Learning-Internship-at-Internity/blob/main/Preprocessing_for_major_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
"""
The fit_on_texts method is a part of Keras tokenizer class which is used to update 
the internal vocabulary for the texts list. 
We need to call be before using other methods of texts_to_sequences or texts_to_matrix.

fit_on_texts.word_index assigns a unique index for each word.
"""
import json 
import re
import numpy as np 
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, GlobalAveragePooling1D
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.preprocessing import LabelEncoder


def pad_sequences(sequences,maxlen,padding = 'pre',value=0):
  padding_sequences = sequences
  if padding=='pre':
    for seq in padding_sequences:
      while(len(seq)<maxlen):
        seq.insert(0,value)
  else:
    for seq in padding_sequences:
      while(len(seq)<maxlen):
        seq.append(value)
  return np.array(padding_sequences)





def texts_to_sequences(training_sentences,word_index):
  seq=[]
  bad_char = [',','?','/','_']
  for sentence in training_sentences:
    w=[]
    for c in bad_char:
      sentence = sentence.replace(c,'')
    for word in sentence.split():
      word = word.lower()
      w.append(word_index[word])
    seq.append(w)
  return seq




def Label_Encoder(training_labels):
  class_array = []
  class_labels = []
  idx = 0
  for data in training_labels:
    if data not in class_array:
      class_array.append(data)
      class_labels.append(idx)
      idx+=1
  num_array = []
  class_array = sorted(class_array)
  d = {class_array[i]:class_labels[i] for i in range(len(class_array))}
  for label in training_labels:
    num_array.append(d[label])
  return(np.array(num_array))





def inverse_transform(similarity_vector,training_labels):
  class_arr = []
  for cls in training_labels:
    if cls not in class_arr:
      class_arr.append(cls)
  max_index = None
  max = 0
  for index in range(len(similarity_vector)):
    if max<similarity_vector[index]:
      max_index = index
      max = similarity_vector[index]
  return class_arr[max_index]
    



  
#print(word)
#print(sentence)
#print(sentence)
#sentence = re.match("[a-zA-Z]+",sentence).group(0)
#sentence = re.sub(r"\W+"," ", sentence)

In [2]:
import nltk
nltk.download('stopwords', quiet = True)
from nltk.corpus import stopwords

stop_words = list(stopwords.words('english'))
#stop_words


In [21]:
def remove_stopwords(stop_words,training_sentences):
  new_sentences = []
  for sentence in training_sentences:
    s = ''
    words = sentence.split()
    for word in words:
      if word not in stop_words:
        s+=(word+' ')
    s=s.strip()
    new_sentences.append(s)
  return new_sentences



In [22]:
with open('intents.json') as file:
    data = json.load(file)


training_sentences = []
training_labels = []
labels = []
responses = []


for intent in data['intents']:
    for pattern in intent['patterns']:
        training_sentences.append(pattern)
        training_labels.append(intent['tag'])
    responses.append(intent['responses'])
    
    if intent['tag'] not in labels:
        labels.append(intent['tag'])

#print(training_labels)
        
num_classes = len(labels)

lbl_encoder = Label_Encoder(training_labels)
print(lbl_encoder)
new_sentences = remove_stopwords(stop_words,training_sentences)
print("training sentences : ",training_sentences)
print("after removing stopwords:")
print("new sentences : ",new_sentences)

vocab_size = 1000
embedding_dim = 16
max_len = 20
oov_token = "<OOV>"

tokenizer = Tokenizer(num_words=vocab_size, oov_token=oov_token) 
tokenizer.fit_on_texts(training_sentences)
word_index = tokenizer.word_index
sequences = texts_to_sequences(training_sentences,word_index)
padded_sequences = pad_sequences(sequences,max_len)

epochs = 550
#history = model.fit(padded_sequences, np.array(training_labels), epochs=epochs)

#print(lbl_encoder.fit_transform(training_labels))
#lbl_encoder.fit(training_labels)
#training_labels = lbl_encoder.transform(training_labels)

#padded_sequences = pad_sequences(sequences, truncating='post', maxlen=max_len)
#tokenizer.texts_to_sequences(training_sentences)
#print(labels,end= "\n\n\n")
#print(training_sentences,end="\n\n\n")
#print(lbl_encoder,end='\n\n\n')

[4 4 4 4 4 4 4 3 3 3 3 3 8 8 8 8 8 6 6 6 6 6 0 0 0 0 0 1 1 1 1 1 2 2 2 2 2
 7 7 7 7 7 5 5 5 5 5]
training sentences :  ['Hi there', 'How are you', 'Is anyone there?', 'Hey', 'Hola', 'Hello', 'Good day', 'Bye', 'See you later', 'Goodbye', 'Nice chatting to you, bye', 'Till next time', 'Thanks', 'Thank you', "That's helpful", 'Awesome, thanks', 'Thanks for helping me', 'How you could help me?', 'What you can do?', 'What help you provide?', 'How you can be helpful?', 'What support is offered', 'How to check Adverse drug reaction?', 'Open adverse drugs module', 'Give me a list of drugs causing adverse behavior', 'List all drugs suitable for patient with adverse reaction', 'Which drugs dont have adverse reaction?', 'Open blood pressure module', 'Task related to blood pressure', 'Blood pressure data entry', 'I want to log blood pressure results', 'Blood pressure data management', 'I want to search for blood pressure result history', 'Blood pressure for patient', 'Load patient blood pressure 

In [5]:
# print(type(padded_sequences))
# print(padded_sequences[0,:].shape)
# print(padded_sequences)


In [6]:
print(word_index)
word_index = dict(sorted(word_index.items()))
#word_index

{'<OOV>': 1, 'blood': 2, 'pressure': 3, 'you': 4, 'for': 5, 'to': 6, 'patient': 7, 'adverse': 8, 'hospital': 9, 'how': 10, 'me': 11, 'drugs': 12, 'pharmacy': 13, 'thanks': 14, 'what': 15, 'reaction': 16, 'list': 17, 'data': 18, 'i': 19, 'want': 20, 'results': 21, 'search': 22, 'find': 23, 'there': 24, 'is': 25, 'bye': 26, 'helpful': 27, 'help': 28, 'can': 29, 'open': 30, 'module': 31, 'a': 32, 'of': 33, 'result': 34, 'lookup': 35, 'hi': 36, 'are': 37, 'anyone': 38, 'hey': 39, 'hola': 40, 'hello': 41, 'good': 42, 'day': 43, 'see': 44, 'later': 45, 'goodbye': 46, 'nice': 47, 'chatting': 48, 'till': 49, 'next': 50, 'time': 51, 'thank': 52, "that's": 53, 'awesome': 54, 'helping': 55, 'could': 56, 'do': 57, 'provide': 58, 'be': 59, 'support': 60, 'offered': 61, 'check': 62, 'drug': 63, 'give': 64, 'causing': 65, 'behavior': 66, 'all': 67, 'suitable': 68, 'with': 69, 'which': 70, 'dont': 71, 'have': 72, 'task': 73, 'related': 74, 'entry': 75, 'log': 76, 'management': 77, 'history': 78, 'load

In [7]:
seq = texts_to_sequences(training_sentences,word_index)
print(seq)

[[36, 24], [10, 37, 4], [25, 38, 24], [39], [40], [41], [42, 43], [26], [44, 4, 45], [46], [47, 48, 6, 4, 26], [49, 50, 51], [14], [52, 4], [53, 27], [54, 14], [14, 5, 55, 11], [10, 4, 56, 28, 11], [15, 4, 29, 57], [15, 28, 4, 58], [10, 4, 29, 59, 27], [15, 60, 25, 61], [10, 6, 62, 8, 63, 16], [30, 8, 12, 31], [64, 11, 32, 17, 33, 12, 65, 8, 66], [17, 67, 12, 68, 5, 7, 69, 8, 16], [70, 12, 71, 72, 8, 16], [30, 2, 3, 31], [73, 74, 6, 2, 3], [2, 3, 18, 75], [19, 20, 6, 76, 2, 3, 21], [2, 3, 18, 77], [19, 20, 6, 22, 5, 2, 3, 34, 78], [2, 3, 5, 7], [79, 7, 2, 3, 34], [80, 2, 3, 21, 5, 7], [23, 2, 3, 21, 81, 82], [23, 11, 32, 13], [23, 13], [17, 33, 83, 84], [85, 13], [22, 13], [35, 5, 9], [86, 5, 9, 6, 87, 7], [19, 20, 6, 22, 9, 18], [9, 35, 5, 7], [88, 89, 9, 90]]


In [8]:
print(padded_sequences)
#padded_sequences2[0,:].shape
# if seq == sequences:
#   print('true')

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 36 24]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 10 37  4]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 25 38 24]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 39]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 40]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 41]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 42 43]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 26]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 44  4 45]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 46]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 47 48  6  4 26]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 49 50 51]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 14]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 52  4]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 53 27]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0